### ISSUE TITLE
コメント記入

### ISSUE THREAD

**Issue by MikamiSyota** [c0a21103/ProjExD#10]
https://github.com/c0a21103/ProjExD/blob/6b9edeff797809283c3ac7e7d05328f5d1b0985e/ex04/dodge_bomb.py#L1-L110
コメントを要所要所に書いてもらうとなにをしているのかわかるのでこちらとしても読みやすいです。もし、可能でしたら書いてみてください

**Comment by c0a21103** [comment]
コメントアウトは修正済みなので確認してみてください
